### PR TITLE
Change BBC Sounds app_id

### PR DESCRIPTION
**Pull request by blawford**
BBC Sounds have changed their app_id.

### CODE REVIEW

**Comment by orbsmiv** [comment]
Just bumping this PR as a bunch of my automations (that rely on playing BBC Radio!) are currently broken.

**Comment by jbeardon** [comment]
Another bump - workaround URLs being used as a temporary measure have now been removed by BBC 😒

**Comment by Jilas** [comment]
I'll add to this, agent the last hour ending what I did to break the radio for my other half.  Only to find the URLs then opened in a browser, just saying GONE.

Any log info etc you need, please ask, likewise happy to help test any solutions.

**Comment by blawford** [comment]
@MartinHjelmare, can you merge this?

**Comment by MartinHjelmare** [comment]
A codeowner should review.

**Comment by blawford** [comment]
> A codeowner should review.

Do you happen to know who that is? I thought I saw you approving dependency version increase PRs.

**Comment by MartinHjelmare** [comment]
Dependency bumps normally don't require you to know the code of the library.

Erik is already tagged two weeks ago. No need to tag him again. When someone has time, they will get around to it.

**Comment by blawford** [comment]
> Dependency bumps normally don't require you to know the code of the library.
> 
> Erik is already tagged two weeks ago. No need to tag him again. When someone has time, they will get around to it.

In this case the only change is a change to an ID, so no code knowledge is really required. 

Sorry, I don't mean to be a pain, I just wasn't sure whether Erik was a Home Assistant employee or whether he might not be active here anymore.

**Review by emontnemery — APPROVED** [review]
Looks good, thanks @blawford 👍

**Comment by orbsmiv** [comment]
This is live in the [Home Assistant 2023.11.3 release](https://github.com/home-assistant/core/releases/tag/2023.11.3) and I can confirm that BBC Sounds casting is working for me.

**Comment by Jilas** [comment]
Strange not sure what I'm doing differently but just updated and still not playing any bbc channel apart from World Service.  Trying to find some logs to see if I can work out what the update hasn't worked for me in the same way.

**Pull request merged**
