### PR TITLE
add support for QUEUE_INSERT

### PR DESCRIPTION
**Pull request by bjesus**
This is aiming to solve issue https://github.com/home-assistant-libs/pychromecast/issues/403 by allowing users to queue new items after the currently playing track.

I've added a `queue_media()` method that works just like `play_media()`, but instead of playing the media immediately it queues it. The Chromecast will automatically play it after the currently playing (and currently queued) media, and users can also skip to it using `queue_next()` etc.

I've also added an example.

### CODE REVIEW

**Comment by bjesus** [comment]
I've fixed some formatting issues and rebased.

**Comment by emontnemery** [comment]
The new code is almost exactly the same as `play_media` + its helper functions.
Can you try refactoring to avoid duplicating so much?

**Comment by bjesus** [comment]
Sure, I can try. Should there still be a `queue_media()` method, or should I just add an optional argument to `play_media()` (eg. `queue=True`) that makes the item queued instead of played?

**Comment by emontnemery** [comment]
An optional parameter `enqueue` sounds good!

**Comment by bjesus** [comment]
I don't have any changes planned :) Thank you!

**Comment by bjesus** [comment]
Is there anything I should fix to help this getting merged?

**Comment by emontnemery** [comment]
Thanks! Do you need a release with the QUEUE_INSERT functionality?

**Comment by bjesus** [comment]
That would be great as I could then submit a patch to `catt` to support this functionality! Thank you!

**Comment by emontnemery** [comment]
OK, it's included in release 7.3.0

**Pull request merged**
